[package]
name = "connection-pool-test-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
bb8-redis = "0.15.0"
tokio = { version = "1.37.0", features = ["full"] }
